export const GET_FAVORITE_FILMS = "GET_FAVORITE_FILMS";
export const GET_FAVORITE_ERROR = "GET_JOBS_ERROR";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const ADD_TO_FAVORITES_ERROR = "ADD_TO_FAVORITES_ERROR";
export const DELETE_FROM_FAVORITES = "DELETE_FROM_FAVORITES";
export const DELETE_FROM_FAVORITES_ERROR = "DELETE_FROM_FAVORITES_ERROR";
